# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: GoTool@0
  inputs:
    version: '1.19.4'

- task: CmdLine@2
  inputs:
    script: |
      export MY_VARIABLE="my value"
      export ARM_CLIENT_ID="$(ARM_CLIENT_ID)"
      export ARM_CLIENT_SECRET="$(ARM_CLIENT_SECRET)"
      export ARM_SUBSCRIPTION_ID="$(ARM_SUBSCRIPTION_ID)"
      export ARM_TENANT_ID="$(ARM_TENANT_ID)"
      echo "Environment Variables exported"
      echo "sub id"
      echo $ARM_SUBSCRIPTION_ID
      echo "tenant id"
      echo $ARM_TENANT_ID
      echo "client secret"
      echo $ARM_CLIENT_SECRET
      echo "client id"
      echo $ARM_CLIENT_ID
      echo "my variable"
      echo $MY_VARIABLE
  displayName: 'Env variables setup'

- task: CmdLine@2
  inputs:
    script: |
      # az login -u "$(username)" -p "$(password)" 
      cd test
      go mod init test
      go mod tidy
      go test -v
  displayName: 'go test'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
